# .github/workflows/python-app.yml

name: Python application CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instala as dependências listadas em requirements.txt (que inclui pytest)
        # Se requirements.txt não existir, este comando falhará, o que é o comportamento esperado.
        python -m pip install -r requirements.txt
        # A linha "pip install pytest" separada foi removida pois pytest já está em requirements.txt

    - name: Test with pytest
      run: |
        pytest